apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImVHRnRlWEE2VEdWMWNuTmxkRFVxIgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: regcred
  namespace: web
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: web
spec:
  selector:
    matchLabels:
      app: web-app
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
        tier: frontend
    spec:
      containers:
        - name: web-app
          image: "xamyp/site-4proj:latest"
          ports:
            - name: http
              containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: web
spec:
  selector:
    matchLabels:
      app: web-api
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: web-api
        tier: backend
    spec:
     containers:
       - name: web-api
         image: "xamyp/back:latest"
         ports:
           - name: api
             containerPort: 8082
     imagePullSecrets:
       - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: web
spec:
  selector:
    app: web-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
  namespace: web
spec:
  selector:
    app: web-api
    tier: backend
  ports:
  - port: 8082
    protocol: TCP
