apiVersion: v1
kind: Namespace
metadata:
  name: react
---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImVHRnRlWEE2VEdWMWNuTmxkRFVxIgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: regcred
  namespace: react
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-4proj-react
  namespace: react
spec:
  selector:
    matchLabels:
      app: react
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: react
        tier: frontend
    spec:
      containers:
        - name: site-4proj
          image: "xamyp/site-4proj:latest"
          ports:
            - name: http
              containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: react
  namespace: react
spec:
  selector:
    app: react
    tier: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: http
